<section id="cuerpocuerpo">
<div id="cuerpo" class="container-fluid bg-2 text-center">
  <h3 class="margin">Si amas la aventuras</h3>
  <p class="undefined"><span style="color: rgb(82, 77, 102); font-family: " source="" sans="" pro";="" font-size:="" 18px;="" text-align:="" start;"="">La palabra “poesía” viene del latín poiesis, que significa “cualidad de crear, hacer o producir”. Se trata de un acto creativo en donde se manifiestan la estética y la belleza a través de la palabra. La poesía es un género literario asociado a la capacidad expresiva y la sensibilidad artística que toma la forma de un verso, o en ocasiones de prosa</span></p>
  <a href="#" class="btn btn-default btn-lg">
    <span class="glyphicon glyphicon-search"></span>&nbsp;</a></div>

<!-- Third Container (Grid) -->
<div id="cuerpo1" class="container-fluid bg-3 text-center">    
  <h2 style="text-align: center; margin: 40px 0px 16px;">Los mejores Poemas cortos</h2>
    <div class="row"><div class="col-sm-4"><p style="text-align: center; margin-top: 8px; margin-bottom: 8px;">Región de manos sucias de pinceles sin pelo</p>
        <p style="text-align: center; margin-top: 8px; margin-bottom: 8px;">de niños boca abajo de cepillos de dientes</p>
        <p style="text-align: center; margin-top: 8px; margin-bottom: 8px;">Zona donde la rata se ennoblece</p>
        <p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">y hay banderas innúmeras y cantan himnos</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">y alguien te prende, hijo de puta,</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">una medalla sobre el pecho</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">Y te pudres lo mismo.</p>
      <img src="https://ziw.es/images/Ssl.PNG" class="img-responsive margin" style="width: 100%; margin: 5px;" alt="Image">
    </div>
    <div class="col-sm-4"> 
      <p style="text-align: center; margin-top: 8px; margin-bottom: 8px;" source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">Todavía tengo casi todos mis dientes</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">casi todos mis cabellos y poquísimas canas</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">puedo hacer y deshacer el amor</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">trepar una escalera de dos en dos</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">y correr cuarenta</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">&nbsp;metros detrás del ómnibus</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">o sea que no debería sentirme viejo</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">pero el grave problema es que antes</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">no me fijaba en estos detalles.</p>
      <img src="https://ziw.es/images/tema4.jpg" class="img-responsive margin " style="width: 100%; margin: 5px;" alt="Image"><img id="40675264" class="imagen" src="https://ziw.es/images/base674.png" style="width: 100%; margin: 5px;">
    </div>
    <div class="col-sm-4"> 
      <p style="text-align: center; margin-top: 8px; margin-bottom: 8px;" source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">Deletreos de armonía</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">que ensaya inexperta mano.</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">Hastío. Cacofonía</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">del sempiterno piano</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">que yo de niño escuchaba</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">soñando... no sé con qué,</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="">con algo que no llegaba,</p><p style="text-align: center; margin-top: 8px; margin-bottom: 8px; font-family: " source="" sans="" pro";="" font-size:="" 18px;="" line-height:="" 30px;="" color:="" rgb(82,="" 77,="" 102);"="" class="">todo lo que ya se fue.</p><img src="https://ziw.es/images/tema6.jpg" class="img-responsive margin" alt="Image" style="width: 410.855px; margin: 5px;"><div style="width:100%;"><img id="25298397" class="imagen" src="https://ziw.es/images/wm2.jpg" style="width: 100%; margin: 5px;"></div>
      
    </div>
  </div>
</div>
<!-- Footer -->
</section>